# Site settings
title: HomeReckers
email: asmikula@uwm.edu
description: > # this means to ignore newlines until "baseurl:"
  HomeReckers are nuts. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://homereck.me" # the base hostname & protocol for your site
twitter_username: homereckers

# Build settings
markdown: kramdown
permalink: pretty
