# Site settings
title: The HomeReckers
email: HomeReckersMKE@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 UWM/Milwaukee area Producer/DJs | Miho x Mikula ~ MKE and Beyond
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://homereck.me" # the base hostname & protocol for your site
twitter_username: homereckers

# Build settings
markdown: kramdown
permalink: pretty
